blog/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls",namespace="users")),
    path('', include("web.urls",namespace="web")),
    path('posts/', include("posts.urls",namespace="posts")),
]

posts/urls.py
from django.urls import path
from posts import views


app_name = "posts"

urlpatterns = [
    path("singlepost/<int:pk>/",views.singlepost,name="singlepost"),
    path("myposts/<int:pk>/",views.myposts,name="myposts"),
    path("create-post/",views.createpost,name="create-post"),
    path("update-post/<int:pk>/",views.updatepost,name="update-post"),
    path("delete-post/<int:pk>/",views.deletepost,name="delete-post"),
]

web/urls.py
from django.urls import path
from web import views


app_name = "web"

urlpatterns = [
    path('',views.index, name="index"),
    path("category/<int:pk>/",views.category,name="category"),
    path("search/",views.search,name="search"),
]

posts/models.py
from django.db import models

# Create your models here.

posts/views.py
import json
from django.http.response import HttpResponseRedirect
from django.shortcuts import render,reverse
from django.shortcuts import redirect, render,get_object_or_404
from django.http.response import HttpResponse

from web.models import Post,Category


def singlepost(request,pk):
    post = get_object_or_404(Post.objects.filter(pk=pk))
    context={
        "post" : post,
    }
    return render(request,"posts/singlepost.html",context=context)


def myposts(request,pk):
    if request.user.is_authenticated:
        posts = Post.objects.filter(is_deleted = False)
        posts = posts.filter(author_id = pk)
        categories = Category.objects.all()
        context = {
            "posts" : posts,
            "categories" : categories
        }
        return render(request,"posts/myposts.html",context=context)
    else:
        return HttpResponseRedirect(reverse("users:login"))
        

def createpost(request):
    if request.user.is_authenticated:
        if request.method == "POST":
            author = request.POST.get("author")
            category = request.POST.get("category")
            title = request.POST.get("title")
            description = request.POST.get("description")

            Post.objects.create( 
                author_id = author,        
                title = title,
                category_id = category,
                description = description
            )

            response_data = {
                "status" : "success",
                "title" : "Successfully added",
                "message" : "Your post is added"
            }
            
            return HttpResponse(json.dumps(response_data), content_type = "application/javascript")
        else:
            categories = Category.objects.all()
            return render(request,"posts/create_post.html",{"categories" : categories })
    else:
        return HttpResponseRedirect(reverse("users:login"))


def updatepost(request,pk):
    if request.user.is_authenticated:
        if request.method == "POST":
            author = request.POST.get("author")
            category = request.POST.get("category")
            title = request.POST.get("title")
            description = request.POST.get("description")

            Post.objects.filter(id = pk).update( 
                author_id = author,        
                title = title,
                category_id = category,
                description = description
            )
            return HttpResponseRedirect(reverse("posts:myposts", kwargs={'pk':author}))
        else:
            posts = Post.objects.filter(is_deleted = False)
            post = get_object_or_404(posts.filter(id = pk))
            categories = Category.objects.all()
            context = {
                "post" : post,
                "categories" : categories
            }
            
            return render(request,"posts/update_post.html",context = context)
    else:
        return HttpResponseRedirect(reverse("users:login"))


def deletepost(request,pk):
    if request.user.is_authenticated:
        Post.objects.filter(id = pk).update( 
            is_deleted = True,        
        )   

        return HttpResponseRedirect(reverse("posts:myposts", kwargs={'pk':request.user.id}))
    else:
        return HttpResponseRedirect(reverse("users:login"))

templates/posts/create_post.html
{% extends "web/base.html" %} 
{% load static %}

{% block content %}

<section id="createpost" class="wrapper">
    <form class="ajax" action="{% url 'posts:create-post' %}" method="POST">
        {% csrf_token %}
        <input type="text" name="author" value={{user.id}} hidden/>
        <label for="category">Category</label>
        <select name="category" id="category" required>
            <option></option>
            {% for category in categories %}
            <option value="{{category.id}}">{{category.name}}</option>
            {% endfor %}
        </select>
        <label for="title">Title</label>
        <input type="text" name="title" id="title" required/>
        <label for="description">Description</label>
        <textarea name="description" id="description" required></textarea><br/>
        <button type="submit">Add</button>
    </form>
</section>

{% endblock %}

templates/posts/myposts.html
{% extends "web/base.html" %} 
{% load static %}

{% block content %}

<section id="myposts" class="wrapper">
    <a class="button create-post" href="{% url 'posts:create-post' %}">Create Post</a>
    <ul>
        {% for post in posts %}
        <li>
            <span class="category">{{post.category}}</span>           
            <h2>{{post.title}}</h2>
            <div class="author-date">
                <span>{{post.date}}</span>
            </div>   
            <p>{{post.description}}</p>
            <a href="{% url 'posts:update-post' pk=post.id %}" class="update_btn button">Update</a>
            <a href="{% url 'posts:delete-post' pk=post.id %}" class="delete_btn button" onclick="return confirm('Are you sure?');">Delete</a>
        </li>
        {% endfor %}
    </ul>    
</section>

{% endblock %}

templates/posts/singlepost.html
{% extends "web/base.html" %} 
{% load static %}

{% block content %}

<section id="singlepost" class="wrapper">
    <span class="category">{{post.category}}</span>
    <h2>{{post.title}}</h2>
    <div class="author-date">
        <span>{{post.author.first_name}} {{post.author.last_name}}</span>
        <span>{{post.date}}</span>
    </div>   
    <p>{{post.description}}</p>
</section>

{% endblock %}

templates/posts/update_post.html
{% extends "web/base.html" %} 
{% load static %}

{% block content %}

<section id="updatepost" class="wrapper">
    
    <form action="{% url 'posts:update-post' pk=post.id %}" method="POST">
        {% csrf_token %}       
        <input type="text" name="author" value={{user.id}} hidden/>
        <label for="category">Category</label>
        <select name="category" >
            {% for category in categories %}
            <option value="{{category.id}}" {% if post.category_id == category.id %} selected {% endif %}>{{category.name}}</option>
            {% endfor %}
        </select>       
        <label for="title">Title</label>
        <input type="text" name="title" value="{{post.title}}" required />
        <label for="description">Description</label>
        <textarea name="description" required>{{post.description}}</textarea><br/>
        
        <button type="submit">Update</button>
    </form>
</section>

{% endblock %}