blog/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls",namespace="users")),
    path('', include("web.urls",namespace="web")),
    path('posts/', include("posts.urls",namespace="posts")),
]

posts/urls.py
from django.urls import path
from posts import views


app_name = "posts"

urlpatterns = [
    path("singlepost/<int:pk>/",views.singlepost,name="singlepost"),
    path("myposts/<int:pk>/",views.myposts,name="myposts"),
    path("create-post/",views.createpost,name="create-post"),
    path("update-post/<int:pk>/",views.updatepost,name="update-post"),
    path("delete-post/<int:pk>/",views.deletepost,name="delete-post"),
]

users/urls.py
from django.urls import path
from users import views


app_name = "users"

urlpatterns = [
    path('login/',views.login, name="login"),
    path('logout/',views.logout, name="logout"),
    path('signup/',views.signup, name="signup"),
]

web/urls.py
from django.urls import path
from web import views


app_name = "web"

urlpatterns = [
    path('',views.index, name="index"),
    path("category/<int:pk>/",views.category,name="category"),
    path("search/",views.search,name="search"),
]

templates/web/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />

    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />

    <title>Blog</title>
</head>
<body>
    <header>
        <h1 class="left">
            <a href="{% url 'web:index' %}"><img src="{% static 'images/logo.png' %}" alt="Logo" /></a>
        </h1>
        <nav class="right">
            {% if request.user.is_authenticated %}
                <span><b>Hi {{request.user.first_name}} {{request.user.last_name}}</b></span>
                <a href="{% url 'posts:myposts' pk=user.id %}" class="button">My posts</a>
                <a href="{% url 'users:logout' %}">Logout</a>
            {% else %}
                <a href="{% url 'users:login' %}">Login</a>
            {% endif %} 
        </nav>
    </header>
    {% block content %}

    {% endblock %}

    <script src="{% static 'js/jquery-3.5.1.min.js' %}"></script>
    <script src="{% static 'js/sweetalert2.min.js' %}"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/web/index.html
{% extends "web/base.html" %} 
{% load static %}

{% block content %}
<section id="spotlight" class="wrapper">
    <nav class="menu">
        <ul>              
            <li><a href="{% url 'web:index' %}" class="active">All</a></li>
            {% for category in categories %}
            <li><a href="{% url 'web:category' pk=category.id %}">{{category.name}}</a></li>
            {% endfor %}
        </ul>
        <div class="search">
            <form action="{% url 'web:search' %}" method="GET">
                <input
                type="search"
                id="query"
                name="query"
                placeholder="What are you looking for?"
                />
                <button type="submit" id="searchButton">
                <i class="fa fa-search"></i>
                </button>
            </form>      
        </div>
    </nav>
    <section class="content">
        <ul>
            {% for post in posts %}
            <li>
                <span class="category">{{post.category}}</span>
                <h3>{{post.title}}</h3>
                <div class="author-date">
                    <span>{{post.author.first_name}} {{post.author.last_name}}</span>
                    <span>{{post.date}}</span>
                </div>                   
                <p>{{post.description}}</p>
                <a href="{% url 'posts:singlepost' pk=post.id %}">Show more...</a>
            </li>
            {% endfor %}
        </ul>
    </section>
</section>
{% endblock %}