blog/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include("users.urls",namespace="users")),
    path('', include("web.urls",namespace="web")),
    path('posts/', include("posts.urls",namespace="posts")),
]

users/urls.py
from django.urls import path
from users import views


app_name = "users"

urlpatterns = [
    path('login/',views.login, name="login"),
    path('logout/',views.logout, name="logout"),
    path('signup/',views.signup, name="signup"),
]

web/urls.py
from django.urls import path
from web import views


app_name = "web"

urlpatterns = [
    path('',views.index, name="index"),
    path("category/<int:pk>/",views.category,name="category"),
    path("search/",views.search,name="search"),
]

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.forms.widgets import EmailInput,TextInput,PasswordInput


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["first_name","last_name","email","username","password"]

        widgets={
            "email":EmailInput(attrs={"placeholder":"Work Email","required":True}),
            "first_name":TextInput(attrs={"placeholder":"First name","required":True}),
            "last_name":TextInput(attrs={"placeholder":"Last name","required":True}),
            "username":TextInput(attrs={"placeholder":"Username","required":True}),
            "password":PasswordInput(attrs={"placeholder":"Password","required":True}),
        }

users/views.py
from django.http.response import HttpResponseRedirect
from django.shortcuts import render,reverse
from django.contrib.auth import authenticate,login as auth_login,logout as auth_logout
from django.contrib.auth.models import User

from users.forms import UserForm


def login(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")

        if username and password:
            user = authenticate(request,username=username, password=password)
            if user is not None:
                auth_login(request,user)
                return HttpResponseRedirect("/")
            else:
                context ={
                "title" : "Login",
                "error" : True,
                "message" : "Invalid username or password"
                }
                return render(request,"users/login.html",context=context)
        else:
            context ={
            "title" : "Login",
            "error" : True,
            "message" : "Invalid username or password"
            }
            return render(request,"users/login.html",context=context)
    else:
        context ={
            "title" : "Login"
        }
        return render(request,"users/login.html",context=context)

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse("web:index"))

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            User.objects.create_user(
                username = instance.username,
                password = instance.password,
                email = instance.email,
                first_name = instance.first_name,
                last_name = instance.last_name
            )

            user = authenticate(request,username=instance.username, password=instance.password)
            auth_login(request,user)

            return HttpResponseRedirect(reverse("web:index"))
        else:
            context ={
            "title" : "Signup",
            "error" : True,
            "message" : "Username already exist"
            }
            return render(request,"users/signup.html",context=context)
    else:    
        form = UserForm()
        context ={
            "title" : "Signup",
            "form" : form,
        }
        return render (request,"users/signup.html",context=context)

templates/users/auth_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css" />

    <title>{{title}}</title>
</head>
<body>   
    {% block content %}

    {% endblock %}
</body>
</html>

templates/users/login.html
{% extends "users/auth_base.html" %} 
{% load static %}

{% block content %}
    <section id="login" class="wrapper">
        <form class="content" action="" method="POST" >
            {% csrf_token %}
            <h1>Login</h1>
            <label for="username">Username</label>
            <input type="text" placeholder="Enter your username" name="username" id="username"/>
            <label for="password">Password</label>
            <input type="password" placeholder="Enter your password" name="password" id="password"/>
            {% if error %}
                <p class="error-message">{{message}}</p>
            {% endif %}
            <button type="submit">Login</button>

            <a href="{% url 'users:signup' %}">Create Account</a>
        </form>
    </section>

{% endblock %}
    

templates/users/signup.html
{% extends "users/auth_base.html" %} 
{% load static %}

{% block content %} 
 <section id="signup" class="wrapper">
        <form class="content" action="" method="POST" >
            <h1>Signup</h1>
            {% csrf_token %}
            {% for field in form %}
                <label for="field.id_for_label">{{field.label}}</label>
                {{field}}
            {% endfor %}
            
            {% if error %}
                <p class="error-message">{{message}}</p>
            {% endif %}
            <button type="submit">Create Account</button>

            <a href="{% url 'users:login' %}">Login</a>
        </form>
    </section>

{% endblock %}
    